version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build_products: # runs not using Workflows must have a `build` job as entry point

    docker: # run the steps with Docker
      - image: circleci/openjdk:10-jdk # ...with this image as the primary container; this is where all `steps` will run


    working_directory: ~/compiler # directory where steps will run

    steps: # a collection of executable commands

      - checkout # check out source code to working directory
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
          key: compiler

      - run: mvn clean package -Pexecutable # run the actual tests
      - run: echo '${project.version}'

      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: compiler

      - persist_to_workspace: 
          root: /home/circleci
          paths:
            - compiler/target/

  deploy_release: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/golang:1.8

    working_directory: ~/compiler # directory where steps will run

    steps: # a collection of executable commands
      - attach_workspace:
          at: /home/circleci
      - run: go get github.com/aktau/github-release
      - run: cd target
      - run: echo "${project.version}"
      - run: export ARTIFACT=`ls *.jar`
      - run: github-release upload --replace --user $CIRCLE_PROJECT_USERNAME --repo $CIRCLE_PROJECT_REPONAME --tag CircleCIRelease --file "compiler-${project.version}.jar" --name 

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy_release:
          requires:
            - build_products
      - build_products
